language: groovy
sudo: false
git:
  depth: 5
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
deploy:
  - provider: script
    skip_cleanup: true
    script: "./gradlew publish"
    on:
      repo: ensime/ensime-gradle
      condition: "$TRAVIS_PULL_REQUEST != false"
      jdk: openjdk6
