language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
script: ./gradlew publish
git:
  depth: 5
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
env:
  global:
  - secure: ji6pnQOFjbI0npyTk3WoNn4fKCpecZmhkAqwr0+Hk0WTyrZ9d5xfDiboyLDPr3ijv9ygiqHpSYSd3YEySKXqfILyUwg5k5jWIE+K9xAioxrmMYTazgfzfBUK2SqtqTz03l1vu1eaBBJ7ezi+VbzFUdg0yGitb0BLX+I0pKOA2Tc=
  - secure: QAzXvepXS0lJi8mO965yocrAO6ENRHrqLLafvwzkuSavQaKcAxxzs2+rAWVk5pvE8LHsK9dkXDFxUg6zVEJjrq3A9Dco3HG0QPTUdKiMutmmFSgJdNbh7ElrQnle40f623MdQ1vaD7oRjCzBUTNU+CPoAUqbmFw6xMDL0BW7FVw=
  - secure: A6OAx8O4FKxuxmEF3xcM2H3oVT41FCpPoG4HLfCmzVvXe1qxuHyf9ql8yGPCgkJ3rCWxq3TozyTrq0p/lf9xrvZDLwbUszcsAgCNuixD8cXT8j75AuArSufMwRky2WXIkqZuz0z0l9WBG+RXyoYHeGgZvLANXJsPYoXoam6q20M=
  - secure: gfrglDadX9+0w/zVzJIbzGcvNH/00zPZ3L7T+ccTXZa6bn3quEbrpsXZDhE9dzwCuYu90mj/1WpOzJ830R+bKRQ+wxfxVmWKbSCo0usCBmElltrSy2p7om1VGF7w0VulDES2Y2KzJDJ00rIjO4hVr5e8ICOfl0Bd6ubTf2E+T08=
  - secure: TS0Fl2ZmuOx+c552ogvLw/6FWkVbwnmu5rcmZ2x6qK7LIAZmMRr5Hu+AkXelFqypFjVnWJa6mWb31mYFSAwxZ19zbbYFMAz0L2JaM9q97stCLYuHMg5rIq9ruMP1EfXkpGtx8zYITITIkYHz9KR74U2R+ih6R/JIHSk4y5o6s7Y=

